name: Azure Terraform Destroy State

on: workflow_dispatch
#  push:
#    branches:
#    - master
#    - 'feature/**'

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
        az storage container delete --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --name ${{ secrets.STORAGE_CONTAINER_NAME }}
        az storage account delete -n {{ secrets.STORAGE_ACCOUNT_NAME }} -g {{ secrets.RESOURCE_GROUP_NAME }}
        az group delete -g {{ secrets.RESOURCE_GROUP_NAME }}