name: Azure Terraform Init State

on: workflow_dispatch
#  push:
#    branches:
#    - master
#    - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        ls