name: Azure Terraform Init State

on: workflow_dispatch
#  push:
#    branches:
#    - master
#    - 'feature/**'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az group create -g {{ secrets.RESOURCE_GROUP_NAME }} -l {{ secrets.STORAGE_REGION_NAME }} 
        az storage account create -n {{ secrets.STORAGE_ACCOUNT_NAME }} -g {{ secrets.RESOURCE_GROUP_NAME }} -l {{ secrets.STORAGE_REGION_NAME }} 
        az storage container create --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --name ${{ secrets.STORAGE_CONTAINER_NAME }}